"""Render a :class:`~graph2skill.bundle.SkillBundle` as skill markdown."""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence

from graph2skill.analyze import ResolvedTree, TreeNodeView
from graph2skill.bundle import SkillBundle
from graph2skill.model import Node, Provenance
from graph2skill.ontology import EN, ZH, node_type_label, relation_label
from graph2skill.util import (
    anchor,
    escape_table_cell,
    fence,
    one_line,
    relative_link,
    slugify,
    truncate,
    yaml_scalar,
)

LABELS: Dict[str, Dict[str, str]] = {
    ZH: {
        "skill_title": "{domain} 决策与排查技能",
        "when_to_use": "适用场景",
        "how_to_use": "使用流程",
        "routing": "场景路由表",
        "col_scenario": "场景 / 入口",
        "col_type": "类型",
        "col_size": "节点数",
        "col_depth": "最大深度",
        "col_file": "参考文件",
        "col_source": "来源",
        "layout": "目录结构",
        "rules": "作答要求",
        "coverage": "覆盖范围与局限",
        "overview": "知识图谱总览",
        "playbook": "排查手册",
        "entry_node": "入口节点",
        "decision_path": "决策路径",
        "diagram": "路径示意图",
        "node_details": "节点详情",
        "description": "说明",
        "observations": "观察 / 现象",
        "commands": "命令与参数示例",
        "provenance": "出处",
        "sources": "数据来源",
        "children": "下一步",
        "extra": "其他字段",
        "catalog": "节点索引",
        "uncovered": "未挂接到决策树的节点",
        "command_index": "命令速查",
        "source_index": "来源文档索引",
        "report": "转换报告",
        "stats": "统计",
        "node_types": "节点类型分布",
        "relation_types": "关系类型分布",
        "issues": "校验结果",
        "merge": "合并情况",
        "no_issues": "未发现结构性问题。",
        "see_above": "（同一节点已在上文展开）",
        "truncated": "（已达深度上限，未继续展开）",
        "in_playbook": "所属手册",
        "excerpt": "原文摘录",
        "generated": "本文件由 {generator} 自动生成，请勿手工编辑；请修改源图后重新生成。",
        "references_count": "{count} 处引用",
        "r_nodes": "节点",
        "r_relations": "关系",
        "r_trees": "决策树",
        "r_commands": "命令示例",
        "r_provenance": "出处记录",
        "r_orphans": "未挂接到决策树的节点",
        "r_inputs": "输入文档数",
        "r_graph_ids": "输入 graphId",
        "r_nodes_read": "读入节点",
        "r_relations_read": "读入关系",
        "r_merged_nodes": "按 id 合并的节点",
        "r_merged_relations": "按 (type, from, to) 合并的关系",
        "r_kept": "保留",
        "r_source_file": "来源文件",
        "r_conflicts": "字段冲突",
        "r_conflict_line": "{kind} `{ref}` 的 `{field}`：采用 {kept}，忽略 {dropped}",
        "r_loader_warnings": "加载告警",
    },
    EN: {
        "skill_title": "{domain} decision & troubleshooting skill",
        "when_to_use": "When to use",
        "how_to_use": "How to use",
        "routing": "Scenario routing table",
        "col_scenario": "Scenario / entry",
        "col_type": "Type",
        "col_size": "Nodes",
        "col_depth": "Max depth",
        "col_file": "Reference file",
        "col_source": "Sources",
        "layout": "Package layout",
        "rules": "Answering rules",
        "coverage": "Coverage and limits",
        "overview": "Graph overview",
        "playbook": "Playbook",
        "entry_node": "Entry node",
        "decision_path": "Decision path",
        "diagram": "Path diagram",
        "node_details": "Node details",
        "description": "Description",
        "observations": "Observations",
        "commands": "Commands and parameter examples",
        "provenance": "Provenance",
        "sources": "Sources",
        "children": "Next steps",
        "extra": "Other fields",
        "catalog": "Node index",
        "uncovered": "Nodes not attached to any decision tree",
        "command_index": "Command index",
        "source_index": "Source document index",
        "report": "Conversion report",
        "stats": "Statistics",
        "node_types": "Node types",
        "relation_types": "Relation types",
        "issues": "Validation",
        "merge": "Merge",
        "no_issues": "No structural problems found.",
        "see_above": "(expanded earlier in this file)",
        "truncated": "(depth limit reached)",
        "in_playbook": "Playbook",
        "excerpt": "Excerpt",
        "generated": "Generated by {generator}; do not edit by hand - regenerate from the source graphs instead.",
        "references_count": "{count} reference(s)",
        "r_nodes": "nodes",
        "r_relations": "relations",
        "r_trees": "decision trees",
        "r_commands": "commands",
        "r_provenance": "provenance records",
        "r_orphans": "nodes outside any tree",
        "r_inputs": "input documents",
        "r_graph_ids": "input graph ids",
        "r_nodes_read": "nodes read",
        "r_relations_read": "relations read",
        "r_merged_nodes": "nodes merged by id",
        "r_merged_relations": "relations merged by (type, from, to)",
        "r_kept": "kept",
        "r_source_file": "source file",
        "r_conflicts": "conflicts",
        "r_conflict_line": "{kind} `{ref}` field `{field}`: kept {kept}, ignored {dropped}",
        "r_loader_warnings": "loader warnings",
    },
}


def t(bundle: SkillBundle, key: str, **fmt: object) -> str:
    table = LABELS.get(bundle.options.lang, LABELS[ZH])
    text = table.get(key, LABELS[ZH].get(key, key))
    return text.format(**fmt) if fmt else text


# ---------------------------------------------------------------------------
# shared fragments
# ---------------------------------------------------------------------------

def _sources_text(items: Sequence[str]) -> str:
    return ", ".join(f"`{item}`" for item in items) if items else "-"


def _provenance_lines(bundle: SkillBundle, items: Sequence[Provenance], indent: str = "") -> List[str]:
    lines: List[str] = []
    for prov in items:
        parts: List[str] = []
        if prov.source_path:
            parts.append(f"`{prov.source_path}`")
        if prov.locator:
            parts.append(one_line(prov.locator))
        if prov.anchor:
            parts.append(f"`{prov.anchor[:23]}…`" if len(prov.anchor) > 24 else f"`{prov.anchor}`")
        head = " · ".join(part for part in parts if part) or "-"
        lines.append(f"{indent}- {head}")
        if prov.excerpt:
            lines.append(f"{indent}  > {truncate(prov.excerpt, bundle.options.excerpt_limit)}")
    return lines


def node_headline(bundle: SkillBundle, node: Node) -> str:
    return f"[{node_type_label(node.type, bundle.options.lang)}] {one_line(node.label)}"


def node_detail_lines(
    bundle: SkillBundle,
    node: Node,
    level: int = 3,
    children: Optional[Sequence[TreeNodeView]] = None,
) -> List[str]:
    """Full markdown block describing one node."""
    hashes = "#" * max(2, min(level, 6))
    lines: List[str] = [f'<a id="{anchor(node.id)}"></a>', "", f"{hashes} {node_headline(bundle, node)}", ""]
    meta: List[str] = [f"`{node.id}`"]
    if node.execution_class:
        meta.append(f"executionClass: `{node.execution_class}`")
    if node.scenario_id and node.scenario_id != node.id:
        meta.append(f"scenarioId: `{node.scenario_id}`")
    if node.sources:
        meta.append(f"{t(bundle, 'sources')}: {_sources_text(node.sources)}")
    if node.source_version:
        meta.append(f"version: `{node.source_version}`")
    lines.append(" · ".join(meta))
    lines.append("")

    description = one_line(node.description)
    if description and description != one_line(node.name):
        lines += [f"**{t(bundle, 'description')}**: {description}", ""]

    observations = [obs for obs in node.observations if one_line(obs) != one_line(node.name)]
    if observations:
        lines.append(f"**{t(bundle, 'observations')}**")
        lines += [f"- {one_line(obs)}" for obs in observations]
        lines.append("")

    if node.commands:
        lines.append(f"**{t(bundle, 'commands')}**")
        lines.append("")
        lines += fence("\n".join(node.commands))
        lines.append("")

    extra = node.extra_data
    if extra:
        lines.append(f"**{t(bundle, 'extra')}**")
        for key, value in extra.items():
            if isinstance(value, (list, dict)):
                rendered = truncate(str(value), 300)
            else:
                rendered = one_line(str(value))
            lines.append(f"- `{key}`: {rendered}")
        lines.append("")

    if children:
        lines.append(f"**{t(bundle, 'children')}**")
        for child in children:
            label = child.node.label if child.node else child.node_id
            edge = relation_label(child.via.type, bundle.options.lang) if child.via else ""
            condition = child.via.condition if child.via else ""
            prefix = f"({edge}) " if edge else ""
            suffix = f" — {one_line(condition)}" if condition and condition != one_line(label) else ""
            lines.append(f"- {prefix}[{one_line(label)}](#{anchor(child.node_id)}){suffix}")
        lines.append("")

    provenance = node.provenance
    if provenance:
        lines.append(f"**{t(bundle, 'provenance')}**")
        lines += _provenance_lines(bundle, provenance)
        lines.append("")
    return lines


# ---------------------------------------------------------------------------
# decision path (nested list) + mermaid diagram
# ---------------------------------------------------------------------------

def decision_path_lines(bundle: SkillBundle, view: TreeNodeView, indent: int = 0) -> List[str]:
    lines: List[str] = []
    pad = "  " * indent
    label = view.node.label if view.node else view.node_id
    edge = relation_label(view.via.type, bundle.options.lang) if view.via else ""
    type_label = node_type_label(view.node.type, bundle.options.lang) if view.node else "?"
    head = f"{pad}- **[{type_label}]** [{one_line(label)}](#{anchor(view.node_id)})"
    if edge and view.depth > 0 and edge != type_label:
        head += f" _{edge}_"
    if view.repeated:
        head += f" {t(bundle, 'see_above')}"
    if view.truncated:
        head += f" {t(bundle, 'truncated')}"
    lines.append(head)
    condition = view.via.condition if view.via else ""
    if condition and view.node and one_line(condition) != one_line(view.node.label):
        lines.append(f"{pad}  - {one_line(condition)}")
    if view.node is not None:
        for command in view.node.commands[:3]:
            lines.append(f"{pad}  - `{one_line(command)}`")
    for child in view.children:
        lines += decision_path_lines(bundle, child, indent + 1)
    return lines


def _mermaid_label(text: str) -> str:
    cleaned = one_line(text).replace('"', "'").replace("[", "(").replace("]", ")")
    cleaned = cleaned.replace("{", "(").replace("}", ")").replace("|", "/")
    return truncate(cleaned, 42)


def mermaid_lines(bundle: SkillBundle, tree: ResolvedTree) -> List[str]:
    """A flowchart of the tree, skipped when it would be unreadable."""
    if not bundle.options.diagrams or len(tree.node_ids) > bundle.options.max_diagram_nodes:
        return []
    ids: Dict[str, str] = {}
    body: List[str] = []
    edges: List[str] = []

    def node_key(node_id: str) -> str:
        if node_id not in ids:
            ids[node_id] = f"N{len(ids)}"
        return ids[node_id]

    def walk(view: TreeNodeView) -> None:
        key = node_key(view.node_id)
        if len(body) == len(ids) - 1:
            label = view.node.label if view.node else view.node_id
            type_label = node_type_label(view.node.type, bundle.options.lang) if view.node else "?"
            body.append(f'    {key}["{_mermaid_label(type_label)}: {_mermaid_label(label)}"]')
        for child in view.children:
            child_key = node_key(child.node_id)
            if len(body) == len(ids) - 1:
                label = child.node.label if child.node else child.node_id
                type_label = node_type_label(child.node.type, bundle.options.lang) if child.node else "?"
                body.append(f'    {child_key}["{_mermaid_label(type_label)}: {_mermaid_label(label)}"]')
            child_type_label = node_type_label(child.node.type, bundle.options.lang) if child.node else ""
            edge_label = relation_label(child.via.type, bundle.options.lang) if child.via else ""
            if edge_label == child_type_label:
                edge_label = ""
            if edge_label:
                edges.append(f'    {key} -->|{_mermaid_label(edge_label)}| {child_key}')
            else:
                edges.append(f"    {key} --> {child_key}")
            if not child.repeated:
                walk(child)

    walk(tree.root)
    if not body:
        return []
    return ["```mermaid", "flowchart TD"] + body + edges + ["```", ""]


# ---------------------------------------------------------------------------
# documents
# ---------------------------------------------------------------------------

MAX_NAME_LENGTH = 64
MAX_DESCRIPTION_LENGTH = 1024


def default_skill_name(bundle: SkillBundle) -> str:
    """Skill name: lowercase, hyphenated, at most 64 characters."""
    if bundle.options.name:
        return slugify(bundle.options.name, fallback="skill", max_length=MAX_NAME_LENGTH)
    base = slugify(bundle.graph.domain or bundle.graph.graph_id, fallback="graph", max_length=MAX_NAME_LENGTH - 9)
    return f"{base}-playbook"[:MAX_NAME_LENGTH]


def default_description(bundle: SkillBundle) -> str:
    if bundle.options.description:
        return truncate(bundle.options.description, MAX_DESCRIPTION_LENGTH)
    domain = bundle.domain
    titles = [tree.title for tree in bundle.trees[:6]]
    stats = bundle.stats
    if bundle.options.lang == EN:
        text = (
            f"Decision playbooks for the {domain} domain, compiled from a knowledge graph of "
            f"{stats.node_count} nodes and {stats.relation_count} relations. Use when diagnosing, "
            f"triaging or explaining {domain} problems: it routes a symptom to the matching decision tree, "
            f"lists candidate causes, checks, commands and reference cases with source citations."
        )
        if titles:
            text += " Covered entries: " + "; ".join(truncate(title, 60) for title in titles) + "."
    else:
        text = (
            f"{domain} 领域的决策与排查手册，由包含 {stats.node_count} 个节点、{stats.relation_count} 条关系的知识图谱生成。"
            f"当需要定位、排查或解释 {domain} 相关问题时使用：按现象路由到对应决策树，给出候选原因、检查项、命令示例与案例出处。"
        )
        if titles:
            text += "覆盖入口：" + "；".join(truncate(title, 40) for title in titles) + "。"
    return truncate(text, MAX_DESCRIPTION_LENGTH)


def render_skill_md(bundle: SkillBundle) -> str:
    options = bundle.options
    stats = bundle.stats
    lines: List[str] = [
        "---",
        f"name: {yaml_scalar(default_skill_name(bundle))}",
        f"description: {yaml_scalar(default_description(bundle))}",
        "---",
        "",
        f"# {options.title or t(bundle, 'skill_title', domain=bundle.domain)}",
        "",
        t(bundle, "generated", generator=options.generator),
        "",
        f"## {t(bundle, 'when_to_use')}",
        "",
    ]
    if options.lang == EN:
        lines += [
            f"- The question is about the **{bundle.domain}** domain (fault symptoms, causes, checks, configuration or cases).",
            f"- {stats.tree_count} decision trees cover {stats.node_count} knowledge nodes and {stats.command_count} command samples.",
            "- Do not use it for domains outside the coverage table below; say so instead of guessing.",
            "",
            f"## {t(bundle, 'how_to_use')}",
            "",
            "1. Match the user's symptom against the routing table and open the matching playbook under `references/playbooks/`.",
            "2. Walk the decision path top-down: check the observations, run the listed commands, then follow the branch whose condition holds.",
            "3. Quote the `provenance` entry (source file + locator) of every node you rely on.",
            "4. If nothing matches, check `references/node-catalog.md` and `references/commands.md` before answering from general knowledge - and say that the answer is outside the graph.",
            "",
        ]
    else:
        lines += [
            f"- 问题属于 **{bundle.domain}** 领域（故障现象、原因定位、检查手段、配置或案例）。",
            f"- 当前图谱含 {stats.tree_count} 棵决策树、{stats.node_count} 个知识节点、{stats.command_count} 条命令示例。",
            "- 超出下方路由表覆盖范围的问题不要臆测，应明确说明未覆盖。",
            "",
            f"## {t(bundle, 'how_to_use')}",
            "",
            "1. 用用户描述的现象匹配路由表，打开 `references/playbooks/` 下对应手册。",
            "2. 自顶向下走决策路径：先核对「观察/现象」，再执行「命令与参数示例」，然后沿条件成立的分支继续。",
            "3. 引用到的每个节点都要带上其 `出处`（来源文件 + 定位），不要凭空断言。",
            "4. 若路由表无匹配项，先查 `references/node-catalog.md` 与 `references/commands.md`；仍无结果时应说明该问题不在图谱覆盖范围内。",
            "",
        ]

    lines += [f"## {t(bundle, 'routing')}", ""]
    lines += _routing_table(bundle)
    lines += ["", f"## {t(bundle, 'layout')}", "", "```", "SKILL.md"]
    lines.append("references/overview.md")
    for tree in bundle.trees:
        lines.append(bundle.playbook_path(tree))
    lines.append("references/node-catalog.md")
    lines.append("references/commands.md")
    lines.append("references/sources.md")
    if options.include_report:
        lines.append("references/conversion-report.md")
    if options.include_graph_asset:
        lines.append("assets/graph.json")
    if options.include_query_script:
        lines.append("scripts/graph_query.py")
    lines.append("```")
    lines.append("")

    if options.include_query_script:
        if options.lang == EN:
            lines += [
                "Look a node up without reading a whole reference file:",
                "",
                "```bash",
                'python scripts/graph_query.py search "LDP session"',
                "python scripts/graph_query.py node cause:isis:isis-75700908-1",
                "python scripts/graph_query.py tree tree:scenario:isis:IS-IS-1",
                "```",
                "",
            ]
        else:
            lines += [
                "无需通读参考文件即可精确查节点：",
                "",
                "```bash",
                'python scripts/graph_query.py search "LDP 会话"',
                "python scripts/graph_query.py node cause:isis:isis-75700908-1",
                "python scripts/graph_query.py tree tree:scenario:isis:IS-IS-1",
                "```",
                "",
            ]

    lines += [f"## {t(bundle, 'coverage')}", ""]
    if options.lang == EN:
        lines += [
            f"- Sources: {_sources_text(list(stats.sources.keys()))}",
            "- Node types: " + ", ".join(f"{node_type_label(k, options.lang)} ({v})" for k, v in stats.node_types.items()),
            f"- {stats.orphan_count} node(s) are not reachable from any entry; they are listed in `references/node-catalog.md`.",
            f"- {len(bundle.errors())} error(s) and {len(bundle.warnings())} warning(s) were found while converting; see `references/conversion-report.md`.",
        ]
    else:
        lines += [
            f"- 数据来源：{_sources_text(list(stats.sources.keys()))}",
            "- 节点类型：" + ", ".join(f"{node_type_label(k, options.lang)}({v})" for k, v in stats.node_types.items()),
            f"- 有 {stats.orphan_count} 个节点未挂接到任何入口，已在 `references/node-catalog.md` 中单列。",
            f"- 转换时发现 {len(bundle.errors())} 个错误、{len(bundle.warnings())} 个告警，详见 `references/conversion-report.md`。",
        ]
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _routing_table(bundle: SkillBundle, from_dir: str = "") -> List[str]:
    header = (
        f"| {t(bundle, 'col_scenario')} | {t(bundle, 'col_type')} | {t(bundle, 'col_size')} | "
        f"{t(bundle, 'col_depth')} | {t(bundle, 'col_source')} | {t(bundle, 'col_file')} |"
    )
    lines = [header, "| --- | --- | --- | --- | --- | --- |"]
    for tree in bundle.trees:
        node = tree.entry_node
        type_label = node_type_label(node.type, bundle.options.lang) if node else "?"
        sources = ", ".join(node.sources) if node and node.sources else ", ".join(tree.sources)
        lines.append(
            "| {title} | {type} | {size} | {depth} | {sources} | [{path}]({path}) |".format(
                title=escape_table_cell(truncate(tree.title, 70)),
                type=escape_table_cell(type_label),
                size=tree.size,
                depth=tree.max_depth,
                sources=escape_table_cell(sources or "-"),
                path=relative_link(bundle.playbook_path(tree), from_dir),
            )
        )
    return lines


def render_playbook(bundle: SkillBundle, tree: ResolvedTree) -> str:
    node = tree.entry_node
    lines: List[str] = [f"# {t(bundle, 'playbook')}: {one_line(tree.title)}", ""]
    meta = [f"{t(bundle, 'entry_node')}: `{tree.entry_node_id}`", f"treeId: `{tree.tree_id}`"]
    if node and node.sources:
        meta.append(f"{t(bundle, 'sources')}: {_sources_text(node.sources)}")
    meta.append(f"{t(bundle, 'col_size')}: {tree.size}")
    lines += ["> " + " · ".join(meta), ""]
    if node and node.description and one_line(node.description) != one_line(node.label):
        lines += [one_line(node.description), ""]

    diagram = mermaid_lines(bundle, tree)
    if diagram:
        lines += [f"## {t(bundle, 'diagram')}", ""] + diagram

    lines += [f"## {t(bundle, 'decision_path')}", ""]
    lines += decision_path_lines(bundle, tree.root)
    lines += ["", f"## {t(bundle, 'node_details')}", ""]

    rendered: set = set()
    for view in tree.root.iter_views():
        if view.node is None or view.node_id in rendered:
            continue
        rendered.add(view.node_id)
        lines += node_detail_lines(bundle, view.node, level=3, children=view.children)
    return "\n".join(lines).rstrip() + "\n"


def render_overview(bundle: SkillBundle) -> str:
    graph = bundle.graph
    stats = bundle.stats
    lines = [f"# {t(bundle, 'overview')}", "", "| key | value |", "| --- | --- |"]
    rows = [
        ("graphId", graph.graph_id),
        ("domain", graph.domain or "-"),
        ("schemaVersion", graph.schema_version),
        ("nodes", str(stats.node_count)),
        ("relations", str(stats.relation_count)),
        ("decisionTrees", str(stats.tree_count)),
        ("entryNodeIds", str(len(graph.entry_node_ids))),
        ("commands", str(stats.command_count)),
        ("provenance", str(stats.provenance_count)),
    ]
    lines += [f"| {escape_table_cell(key)} | {escape_table_cell(value)} |" for key, value in rows]
    lines += ["", f"## {t(bundle, 'node_types')}", "", f"| {t(bundle, 'col_type')} | count |", "| --- | --- |"]
    for node_type, count in stats.node_types.items():
        lines.append(f"| {escape_table_cell(node_type_label(node_type, bundle.options.lang))} (`{node_type}`) | {count} |")
    lines += ["", f"## {t(bundle, 'relation_types')}", "", f"| {t(bundle, 'col_type')} | count |", "| --- | --- |"]
    for rel_type, count in stats.relation_types.items():
        lines.append(f"| {escape_table_cell(relation_label(rel_type, bundle.options.lang))} (`{rel_type}`) | {count} |")
    lines += ["", f"## {t(bundle, 'routing')}", ""] + _routing_table(bundle, from_dir="references")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_catalog(bundle: SkillBundle) -> str:
    lines = [f"# {t(bundle, 'catalog')}", ""]
    by_type: Dict[str, List[Node]] = {}
    for node in bundle.graph.nodes.values():
        by_type.setdefault(node.type, []).append(node)
    for node_type in sorted(by_type, key=lambda key: (-len(by_type[key]), key)):
        nodes = sorted(by_type[node_type], key=lambda item: item.id)
        lines += [
            f"## {node_type_label(node_type, bundle.options.lang)} (`{node_type}`, {len(nodes)})",
            "",
            f"| id | {t(bundle, 'col_scenario')} | {t(bundle, 'in_playbook')} |",
            "| --- | --- | --- |",
        ]
        for node in nodes:
            tree = bundle.tree_for_node(node.id)
            target = (
                f"[{escape_table_cell(truncate(tree.title, 40))}]"
                f"({relative_link(bundle.playbook_path(tree), 'references')}#{anchor(node.id)})"
                if tree
                else "-"
            )
            lines.append(f"| `{escape_table_cell(node.id)}` | {escape_table_cell(truncate(node.label, 80))} | {target} |")
        lines.append("")

    uncovered = bundle.uncovered_node_ids()
    if uncovered:
        lines += [f"## {t(bundle, 'uncovered')} ({len(uncovered)})", ""]
        for node_id in uncovered:
            node = bundle.graph.nodes[node_id]
            lines += node_detail_lines(bundle, node, level=3)
    return "\n".join(lines).rstrip() + "\n"


def render_commands(bundle: SkillBundle) -> str:
    lines = [f"# {t(bundle, 'command_index')}", ""]
    rows: List[str] = []
    for node in sorted(bundle.graph.nodes.values(), key=lambda item: item.id):
        tree = bundle.tree_for_node(node.id)
        for command in node.commands:
            location = (
                f"[{escape_table_cell(truncate(tree.title, 30))}]"
                f"({relative_link(bundle.playbook_path(tree), 'references')}#{anchor(node.id)})"
                if tree
                else f"[node-catalog](node-catalog.md#{anchor(node.id)})"
            )
            rows.append(
                f"| `{escape_table_cell(truncate(command, 120))}` | {escape_table_cell(truncate(node.label, 50))} | {location} |"
            )
    if not rows:
        lines.append("-")
        return "\n".join(lines) + "\n"
    lines += [f"| command | {t(bundle, 'col_scenario')} | {t(bundle, 'in_playbook')} |", "| --- | --- | --- |"]
    lines += rows
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_sources(bundle: SkillBundle) -> str:
    lines = [f"# {t(bundle, 'source_index')}", ""]
    by_path: Dict[str, List[tuple]] = {}
    for node in bundle.graph.nodes.values():
        for prov in node.provenance:
            by_path.setdefault(prov.source_path or "(unknown)", []).append((node, prov))
    for relation in bundle.graph.relations.values():
        for prov in relation.provenance:
            by_path.setdefault(prov.source_path or "(unknown)", []).append((relation, prov))
    if not by_path:
        lines.append("-")
        return "\n".join(lines) + "\n"
    for source_path in sorted(by_path):
        entries = by_path[source_path]
        lines += [f"## `{source_path}`", "", t(bundle, "references_count", count=len(entries)), ""]
        seen: set = set()
        for owner, prov in entries:
            key = (prov.locator, prov.excerpt[:60])
            if key in seen:
                continue
            seen.add(key)
            owner_label = getattr(owner, "label", None) or getattr(owner, "id", "")
            head = prov.locator or owner_label
            lines.append(f"- **{escape_table_cell(truncate(head, 100))}** — `{getattr(owner, 'id', '')}`")
            if prov.excerpt:
                lines.append(f"  > {truncate(prov.excerpt, bundle.options.excerpt_limit)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_report(bundle: SkillBundle) -> str:
    lines = [f"# {t(bundle, 'report')}", "", f"## {t(bundle, 'stats')}", ""]
    stats = bundle.stats
    lines += [
        f"- {t(bundle, 'r_nodes')}: {stats.node_count}",
        f"- {t(bundle, 'r_relations')}: {stats.relation_count}",
        f"- {t(bundle, 'r_trees')}: {stats.tree_count}",
        f"- {t(bundle, 'r_commands')}: {stats.command_count}",
        f"- {t(bundle, 'r_provenance')}: {stats.provenance_count}",
        f"- {t(bundle, 'r_orphans')}: {stats.orphan_count}",
        "",
    ]
    report = bundle.merge_report
    if report is not None:
        lines += [f"## {t(bundle, 'merge')}", ""]
        kept = t(bundle, "r_kept")
        lines += [
            f"- {t(bundle, 'r_inputs')}: {len(report.origins)}",
            f"- {t(bundle, 'r_graph_ids')}: {', '.join(f'`{gid}`' for gid in report.graph_ids) or '-'}",
            f"- {t(bundle, 'r_nodes_read')}: {report.node_total_in} → {kept} {stats.node_count}",
            f"- {t(bundle, 'r_relations_read')}: {report.relation_total_in} → {kept} {stats.relation_count}",
            f"- {t(bundle, 'r_merged_nodes')}: {len(report.merged_node_ids)}",
            f"- {t(bundle, 'r_merged_relations')}: {len(report.merged_relation_keys)}",
            "",
        ]
        for origin in report.origins:
            lines.append(f"- {t(bundle, 'r_source_file')}: `{origin}`")
        lines.append("")
        if report.conflicts:
            lines += [f"### {t(bundle, 'r_conflicts')}", ""]
            lines += [
                "- "
                + t(
                    bundle,
                    "r_conflict_line",
                    kind=conflict.kind,
                    ref=escape_table_cell(conflict.ref),
                    field=conflict.field,
                    kept=escape_table_cell(truncate(str(conflict.kept), 80)),
                    dropped=escape_table_cell(truncate(str(conflict.dropped), 80)),
                )
                for conflict in report.conflicts
            ]
            lines.append("")
        if report.warnings:
            lines += [f"### {t(bundle, 'r_loader_warnings')}", ""]
            lines += [f"- {escape_table_cell(warning)}" for warning in report.warnings]
            lines.append("")

    lines += [f"## {t(bundle, 'issues')}", ""]
    if not bundle.issues:
        lines += [t(bundle, "no_issues"), ""]
    else:
        lines += ["| severity | code | message | ref |", "| --- | --- | --- | --- |"]
        for issue in bundle.issues:
            lines.append(
                f"| {issue.severity} | `{issue.code}` | {escape_table_cell(issue.message)} | `{escape_table_cell(issue.ref)}` |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
